# Force Kafka to use IP address to bypass hostname resolution issues
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# OSRM Configuration
osrm.base-url=http://router.project-osrm.org

# Server Configuration
server.port=8083
