server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

notification:
  webhook:
    enabled: ${NOTIFICATION_WEBHOOK_ENABLED:false}
    url: ${NOTIFICATION_WEBHOOK_URL:https://webhook.site/a1779324-048b-4492-bc3e-2fd3cef812f3}
